### ISSUE TITLE
Error: org.atdl4j.ui.swing.app.iml.SwingAtdl4jTesterApp.java

### ISSUE THREAD

**Issue by waleed3011** [atdl4j/atdl4j#32]
java.lang.ClassNotFoundException: org.atdl4j.ui.swing.app.impl.SwingAtdl4jTesterApp.java
	at java.net.URLClassLoader.findClass(Unknown Source)
	at com.sun.jnlp.JNLPClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at com.sun.jnlp.JNLPClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at com.sun.javaws.Launcher.doLaunchApp(Unknown Source)
	at com.sun.javaws.Launcher.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by mer-rcm-fix** [comment]
*BUMP*
repo links are dead in POM (linking to googlecode)

**Comment by TyAshley** [comment]
The project has been updated to 4.0.0 and the Swing Tester App has been validated to work in the new release. Please reopen if you continue having issues with the tester app.
