### ISSUE TITLE
SWT: Selecting a market without a region filter being selected throws an Exception that isn't caught

### ISSUE THREAD

**Issue by croydondias** [atdl4j/atdl4j#5]
``` java
Exception in thread "main" java.lang.IllegalArgumentException: Region is required when Country is specified.
        at org.atdl4j.ui.swt.app.impl.SWTAtdl4jInputAndFilterDataPanel.extractAtdl4jOptionsFromScreen(SWTAtdl4jInputAndFilterDataPanel.java:382)
        at org.atdl4j.ui.swt.app.impl.SWTAtdl4jInputAndFilterDataSelectionPanel.buttonOkSelected(SWTAtdl4jInputAndFilterDataSelectionPanel.java:87)
        at org.atdl4j.ui.swt.app.impl.SWTAtdl4jInputAndFilterDataSelectionPanel.access$100(SWTAtdl4jInputAndFilterDataSelectionPanel.java:23)
        at org.atdl4j.ui.swt.app.impl.SWTAtdl4jInputAndFilterDataSelectionPanel$2.widgetSelected(SWTAtdl4jInputAndFilterDataSelectionPanel.java:118)
        at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
        at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
        at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
        at org.atdl4j.ui.swt.app.impl.SWTAtdl4jTesterApp.mainLine(SWTAtdl4jTesterApp.java:92)
        at org.atdl4j.ui.swt.app.impl.SWTAtdl4jTesterApp.main(SWTAtdl4jTesterApp.java:44)
```

**Comment by TyAshley** [comment]
This is corrected with the latest release 4.0.1.
